### ISSUE TITLE
Addlayer Undefined Issue

### ISSUE THREAD

**Issue by mrgopal15** [slutske22/react-leaflet-arrowheads#10]
When I Try to Implement react-leaflet-arrowheads to my react map application. I am facing the following error on my Maplayer.js

_**error:**_
MapLayer.js:40 Uncaught TypeError: Cannot read property 'addLayer' of undefined
    at Polyline.componentDidMount (MapLayer.js:40)

and my Maplayer.js is here

```
import type { Layer } from 'leaflet'
import React, { Fragment } from 'react'

import { LeafletProvider } from './context'
import MapComponent from './MapComponent'
import type { LeafletContext, MapLayerProps } from './types'

export default class MapLayer<
  LeafletElement: Layer,
  Props: MapLayerProps,
> extends MapComponent<LeafletElement, Props> {
  contextValue: ?LeafletContext
  leafletElement: LeafletElement

  constructor(props: Props) {
    super(props)
    this.leafletElement = this.createLeafletElement(props)
  }

  get layerContainer(): Layer {
    return this.props.leaflet.layerContainer || this.props.leaflet.map
  }

  createLeafletElement(_props: Props): LeafletElement {
    throw new Error('createLeafletElement() must be implemented')
  }

  updateLeafletElement(_fromProps: Props, _toProps: Props) {}

  componentDidMount() {
    super.componentDidMount()
    this.layerContainer.addLayer(this.leafletElement)
  }

  componentDidUpdate(prevProps: Props) {
    super.componentDidUpdate(prevProps)

    if (this.props.attribution !== prevProps.attribution) {
      const { map } = this.props.leaflet
      if (map != null && map.attributionControl != null) {
        map.attributionControl.removeAttribution(prevProps.attribution)
        map.attributionControl.addAttribution(this.props.attribution)
      }
    }

    this.updateLeafletElement(prevProps, this.props)
  }

  componentWillUnmount() {
    super.componentWillUnmount()
    this.layerContainer.removeLayer(this.leafletElement)
  }

  render() {
    const { children } = this.props
    if (children == null) {
      return null
    }
    return this.contextValue == null ? (
      <Fragment>{children}</Fragment>
    ) : (
      <LeafletProvider value={this.contextValue}>{children}</LeafletProvider>
    )
  }
}
```
Can you help me on that

**Comment by slutske22** [comment]
What version of react-leaflet are you using?

Where are you trying to use `Polyline` from react-lealfet-arrowheads?  

What is the value of `this.contextValue` in your provider? 

 What is `MapComponent`?  

Are you having issue using the regular react-lealfet `Polyline`?

**Comment by mrgopal15** [comment]
What version of react-leaflet are you using?  ->  **"react-leaflet": "^2.6.1",**

Where are you trying to use Polyline from react-lealfet-arrowheads? - > Inside my map component

```
<Map
              srs="EPSG:4326"
              center={[this.state.lat, this.state.lng]}
              zoom={this.state.zoom}
              style={mapview}
              noWrap="true"
              projection="EPSG:4326"
              bbox="[-180.0, -90.0, 180.0, 90.0]"
            > 
<Polyline positions={ [polylinearray] } arrowheads />
</Map>
```


What is the value of this.contextValue in your provider? - **Sorry, How can I find that one? I am new with the map module.**

What is MapComponent? - React Leaflet components

Mapcomponent.js


```
import MapEvented from './MapEvented'
import type { MapComponentProps } from './types'

export default class MapComponent<
  LeafletElement,
  Props: MapComponentProps,
> extends MapEvented<LeafletElement, Props> {
  getOptions(props: Props): Props {
    if (props.pane != null) {
      return props
    }
    if (props.leaflet != null && props.leaflet.pane != null) {
      return { ...props, pane: props.leaflet.pane }
    }
    return props
  }
}
```


Are you having issue using the regular react-lealfet Polyline? - **No, only using other plugins like Arrowhead and Track play, I am facing the same Issue**

**Comment by slutske22** [comment]
I'm confused.  I realized that your `MapLayer.js` is just a copy paste from the react-lealfet source.  The same is true for your `MapComponent.js`.  Did you copy and paste these files into your source code?  Or did you import them from react-leaflet?  If you are having issues with multiple plugins, this is probably not an issue with react-leaflet-arrowheads, but rather with the way you are constructing your map and the way the `LeafletProvider` is passing the context value.  I recommend creating a reproducible example on a codesandbox so I can see the whole picture of your issue.  From the way you're describing it, I'm having trouble understanding what code is react-lealfet source code, what code is yours, and how components are being used.

**Comment by mrgopal15** [comment]
@slutske22 Brother, I fixed the issue. Previously I did a mistake to call from the local. Now I import them from the react-leaflet.

Thanks for your Guidance. Now I am close to the issue.
