### ISSUE TITLE
Update to support react-leaflet v3

### ISSUE THREAD

**Issue by vanbouzoukas** [slutske22/react-leaflet-arrowheads#18]
Hi, are you planning on updating the library to support the latest version of react-leaflet? Thanks.

**Comment by slutske22** [comment]
Its definitely not been on my list of priorities.  I did create a react-leaflet v3 version of this in my other repo, react-leaflet-custom-components.  You can see that here: https://github.com/slutske22/react-leaflet-custom-components/blob/master/src/ArrowheadsPolyline.js - its almost identical to this plugin source code, just adapted to work with v3.

I recommend you either use that code, or create your own custom component based on leaflet-arrowheads.  That will give you an immediate solution.  I don't see myself having time to devote to upgrading this plugin any time soon.

**Comment by vanbouzoukas** [comment]
Excellent, thank you @slutske22! I was able to get it working.
