### ISSUE TITLE
this._arrowheads.remove is not a function

### ISSUE THREAD

**Issue by ksimenic** [slutske22/react-leaflet-arrowheads#3]
I created sandbox with the problem. [[LINK]](https://codesandbox.io/embed/react-leaflet-arrowheads-bug-m1zp3?fontsize=14&hidenavigation=1&theme=dark)

To reproduce, do the following:
1. On the top right on the map there is layers icon, click on it to get a menu
2. Check the "Path" checkbox to show the path - **path showed correctly**
3. Un-check the "Path" checkbox to hide the path - **path hidden correctly**
4. Check it again -> **you should get an error**

Thank you for helping the community 😃

**Comment by slutske22** [comment]
This is an interesting problem...thanks for bringing this to my attention, I had never come across this use case before.  I'll look into it as soon as I can.

**Comment by ksimenic** [comment]
I managed to locate the root of the problem. In the original package (leaflet-arrowheads) there is a function buildVectorHats in src/leaflet-arrowheads.js. The function starts with this check

```
   buildVectorHats: function( options ){

      // Reset variables from previous this._update()
      if (this._arrowheads){
         this._arrowheads.remove()
         let arrowheads = []
         let allhats = []
      }
```

On first check (from my original comment) "this._arrowheads" is "undefined", and on the another check it is empty array.

If it is empty array, this condition will pass and it will call the remove() function which causes the problem. 

A way to prevent this is to add additional check like 
`if (this._arrowheads && this._arrowheads.length > 0)`.

Tried it on my local env and it works fine. I can submit PR on the original package some time tomorrow if you don't do it earlier.

**Comment by slutske22** [comment]
Thank you so much for your PR in the original repo.  [I answered you there.](https://github.com/slutske22/leaflet-arrowheads/pull/8#issuecomment-625593224).  The issue should be solved now - just upgrade `react-leaflet-arrowheads` to 1.0.6.  Let me know if you're still running into problems.
