### ISSUE TITLE
Usage exampel is wrong

### ISSUE THREAD

**Issue by mvoss96** [slutske22/react-leaflet-arrowheads#5]
Hi, I noticed that the usage example is wrong:

If you try to include it like :
import { Polyline } from 'react-leaflet-arrowheads'

it wont work and react will throw an error.
Instead you have to include it like:
import  Polyline  from 'react-leaflet-arrowheads'

**Comment by slutske22** [comment]
Thanks for the heads up!  I fixed it. :blush:
