### ISSUE TITLE
Using arrowheads with GeoJSON

### ISSUE THREAD

**Issue by istvanhajdu** [slutske22/react-leaflet-arrowheads#8]
Due to the better performance I use GeoJSON component to render thousands of LineStrings. Is there any way to use arrowheads with GeoJSON component? Thanks in advance!

**Comment by slutske22** [comment]
Thanks for your interest.  I had never thought about that before.  I'm not sure I understand the idea that GeoJSON gives better performance, especially considering [L.GeoJSON converts 'LineString' and 'MultiLineString' features into L.Polylines](https://gis.stackexchange.com/questions/184482/leaflet-geojson-vs-polyline).  

However, I agree it would be a nice feature to be able to apply arrowheads directly to GeoJSON line features.  I'll see if I can carve out some time to add it to the underlying leaflet-arrowheads plugin and then bring it into the react version.  Hopefully you're not in a rush...

**Comment by istvanhajdu** [comment]
Thank your for your quick and detailed reply! You are right, rendering vector layers and geoJSON are both have proper performance, the only differentiation derived from my code.  Nonetheless the mentioned feature would be very useful. Thank's the effort!

**Comment by slutske22** [comment]
Ok my friend, its ready.  I updated the underlying leaflet-arrowheads package to make this work.  Interestingly, you don't actually need react-leaflet-arrowheads to make this work.  You'd do something like this:

````javascript
// with your imports
import 'leaflet-arrowheads'

// In your <Map />
<GeoJSON data={geojsondata} arrowheads />
````

You can also do an `arrowheads={ <options> }` to customize the arrowheads to your liking.

## [Working Demo](https://codesandbox.io/s/rl-arrowheads-geojson-test-z8qwx) ##

Your request made me realize that I can make `arrowheads` installable as an option on an `L.polyline`, which means I wouldn't need the react-leaflet-arrowheads package at all anyway.  Thanks for the request, it just helped me improve my package.

If you run into any other issues, let me know.
