### ISSUE TITLE
Missing _pointToLayer when arrowheads props not used in GeoJSON component

### ISSUE THREAD

**Issue by istvanhajdu** [slutske22/react-leaflet-arrowheads#9]
First of all thank you very much for your latest feature which helped me to use your plugin with GeoJSON component. It worked well until I tried to use GeoJSON component without your plugin. Then I got the following error message:

```error
ReferenceError
_pointToLayer is not defined
```

I tried to follow the error message and I have found that [_pointToLayer](https://github.com/slutske22/leaflet-arrowheads/blob/master/src/leaflet-arrowheads.js#L470) is not defined in your original plugin. If I add [this](https://github.com/Leaflet/Leaflet/blob/master/src/layer/GeoJSON.js#L225) function to your code (see below), then the plugin works well without any errors.

```javascript
L.GeoJSON.include({
  function _pointToLayer(pointToLayerFn, geojson, latlng, options) {
    return pointToLayerFn ?
      pointToLayerFn(geojson, latlng) :
      new Marker(latlng, options && options.markersInheritOptions && options);
  }
  
   switch (geometry.type) {
      case 'Point':
         latlng = _coordsToLatLng(coords);
         return  this._pointToLayer(pointToLayer, geojson, latlng, options);
      ... 
  }
  ...
 })
```

I forked your GeoJSON sandbox example and I created an [example](https://codesandbox.io/s/rl-arrowheads-v2-example-forked-5vsss?file=/src/Map.js) with the mentioned problem. If I overlooked something please let me know. Thank's in advance!

**Comment by slutske22** [comment]
Thanks for catching this.  I fixed it.  bump your leaflet-arrowheads to v1.2.1 and you should be good.  [Here's your problem sandbox forked with the new version](https://codesandbox.io/s/rl-arrowheads-v2-example-forked-kjxgm), you'll see it works now.

Thanks again
